In [1]:
import pandas as pd
import numpy as np
import random
import json
import pymysql
import mysql.connector

instalar: pip install mysql-connector-python

In [3]:
user='root'
password='astro123'
host='localhost'
database='psociales'


# coneccion con MySQL
conn= mysql.connector.connect(user=user, 
                             password=password,
                             host=host,
                             database=database)
cursor = conn.cursor()
# column names

# consulta
query = 'SELECT *FROM productores_mun2;'

# base
cursor.execute(query)
# nombre de campos
column_names = [i[0] for i in cursor.description]
# lectura de base
base = cursor.fetchall() 
# dataframe
base_productores = pd.DataFrame(base, columns=column_names)
# cierre de la conección
cursor.close()
conn.close()
# imprimimos primeras líneas
base_productores.head()

,cve_ent,entidad,cve_mun,municipio,productores,escenario_marginacion,escenario_precio,latitud,longitud,im,gm,imn
0,04,Campeche,011,Candelaria,53,5.1,2.1,18.1835,-91.0463,50.5139,Alto,0.790978
1,06,Colima,002,Colima,32,5.1,2.1,19.2429,-103.7280,59.7712,Muy bajo,0.935933
2,06,Colima,004,Coquimatlán,46,5.1,2.1,19.2010,-103.8110,57.1252,Muy bajo,0.894501
3,06,Colima,005,Cuauhtémoc,227,5.1,2.1,19.3288,-103.6020,58.1701,Muy bajo,0.910862
4,06,Colima,010,Villa de Álvarez,3,5.1,2.1,19.2648,-103.7370,60.5121,Muy bajo,0.947535